# -*- coding: utf-8 -*-
"""dsa_info.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ff2hEr-8RTZ4zmNSBaenzjul8W7CD51O
"""

import pandas as pd
import numpy as np

class info_data:
  def __init__(self,df):
    self.df=df
  def describe_data(self):
    print(self.head())
    print(self.describe())



a = info_data.describe_data('FIFA-21 Complete.csv')

